export const mainTabs = [
  {
    name: 'index',
    href: '/',
    label: 'Home',
    sf: { default: 'house', selected: 'house.fill' },
    md: 'home',
    symbol: { ios: 'house', android: 'home', web: 'home' },
  },
  {
    name: 'appointments',
    href: '/appointments',
    label: 'Visits',
    sf: { default: 'calendar', selected: 'calendar.circle.fill' },
    md: 'event',
    symbol: { ios: 'calendar', android: 'event', web: 'event' },
  },
  {
    name: 'progress-gallery',
    href: '/progress-gallery',
    label: 'Photos',
    sf: { default: 'photo.on.rectangle', selected: 'photo.fill.on.rectangle.fill' },
    md: 'photo_library',
    symbol: { ios: 'photo.on.rectangle', android: 'photo_library', web: 'photo_library' },
  },
  {
    name: 'payments',
    href: '/payments',
    label: 'Pay',
    sf: { default: 'creditcard', selected: 'creditcard.fill' },
    md: 'payments',
    symbol: { ios: 'creditcard', android: 'payments', web: 'payments' },
  },
  {
    name: 'more',
    href: '/more',
    label: 'More',
    sf: { default: 'ellipsis.circle', selected: 'ellipsis.circle.fill' },
    md: 'more_horiz',
    symbol: { ios: 'ellipsis.circle', android: 'more_horiz', web: 'more_horiz' },
  },
] as const;
